(ml-agents-node) C:\Users\capstone\Documents\GitHub\Double_Agent\Assets\Config>mlagents-learn ./trainer_config.yaml --run-id node_001


                        
                        ___¦¦¦¦
                   +¦¦¦¦¦¦¦¦¦¦¦¦
              ,___m¯¯¯'  ,¦¦¦¯¦¦_                           ¦¦¦  ¦¦¦
            _¦¦¦¯'      _¦¦¯  ¦¦¦      __     __ ,__ ____   ,__ _¦¦¦_ ___    ,__
          _¦¦¦¯        _¦¦¯   ¦¦¦¦     ¦¦¦   ¦¦¦ ¦¦¦¦¯¯¯¦¦¦ ¦¦¦ ¯¦¦¦¯ ^¦¦¦  +¦¦¦
        _¦¦¦¦¦________¦¦¦      ¦¯      ¦¦¦   ¦¦¦ ¦¦¦    ¦¦¦ ¦¦¦  ¦¦¦   ¦¦¦_ ¦¦¦
        ¯¦¦¦¦¯¯¯¯¯¯¯¯¯¯¦¦_     ¦¦      ¦¦¦   ¦¦¦ ¦¦¦    ¦¦¦ ¦¦¦  ¦¦¦    ¦¦¦¦¦¦
          ^¦¦¦¦        ¯¦¦_   ¦¦¦¦     ¦¦¦¦_¦¦¦¦ ¦¦¦    ¦¦¦ ¦¦¦  ¦¦¦_    ¦¦¦¦`
            '¯¦¦¦_      ^¦¦¦  ¦¦¦       +¯¯¯¯ ¯¯ ^¯¯    `¯¯ `¯¯   '¯¯    ¦¦¦¦
               ¯¯¯¯¦___   ¦¦¦¦¦¦,                                      ¦¦¦¦¯
                   `¯¦¦¦¦¦¦¦¦¦¦¦
                        ¬`¯¯¯¦¦


 Version information:
  ml-agents: 0.23.0,
  ml-agents-envs: 0.23.0,
  Communicator API: 1.3.0,
  PyTorch: 1.7.1
2021-02-25 16:55:55 INFO [learn.py:275] run_seed set to 8285
2021-02-25 16:55:56 INFO [environment.py:204] Listening on port 5004. Start training by pressing the Play button in the Unity Editor.
2021-02-25 16:56:00 INFO [environment.py:110] Connected to Unity environment with package version 1.0.6 and communication version 1.0.0
2021-02-25 16:56:00 INFO [environment.py:271] Connected new brain:
Node_AI?team=0
2021-02-25 16:56:00 INFO [stats.py:145] Hyperparameters for behavior name Node_AI:
        trainer_type:   sac
        hyperparameters:
          learning_rate:        0.0003
          learning_rate_schedule:       constant
          batch_size:   100
          buffer_size:  50000
          buffer_init_steps:    0
          tau:  0.005
          steps_per_update:     1.0
          save_replay_buffer:   True
          init_entcoef: 0.5
          reward_signal_steps_per_update:       1.0
        network_settings:
          normalize:    False
          hidden_units: 256
          num_layers:   2
          vis_encode_type:      simple
          memory:       None
        reward_signals:
          extrinsic:
            gamma:      0.99
            strength:   1.0
        init_path:      none
        keep_checkpoints:       5
        checkpoint_interval:    500000
        max_steps:      5000000
        time_horizon:   128
        summary_freq:   50000
        threaded:       True
        self_play:
          save_steps:   20000
          team_change:  80000
          swap_steps:   5000
          window:       10
          play_against_latest_model_ratio:      0.5
          initial_elo:  1200.0
        behavioral_cloning:     None
        framework:      pytorch
2021-02-25 16:56:00 INFO [model_serialization.py:104] Converting to results\node_001\Node_AI\Node_AI-0.onnx
2021-02-25 16:56:02 INFO [model_serialization.py:116] Exported results\node_001\Node_AI\Node_AI-0.onnx
2021-02-25 16:56:02 INFO [trainer.py:115] Saving Experience Replay Buffer to results\node_001\Node_AI\last_replay_buffer.hdf5
2021-02-25 16:56:02 INFO [torch_model_saver.py:116] Copied results\node_001\Node_AI\Node_AI-0.onnx to results\node_001\Node_AI.onnx.
2021-02-25 16:56:02 INFO [trainer.py:115] Saving Experience Replay Buffer to results\node_001\Node_AI\last_replay_buffer.hdf5
2021-02-25 16:56:02 INFO [trainer_controller.py:85] Saved Model
2021-02-25 16:56:02 WARNING [learn.py:185] Unable to save to results\node_001\run_logs\timers.json. Make sure the directory exists
Traceback (most recent call last):
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\learn.py", line 153, in run_training
    tc.start_learning(env_manager)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\trainer_controller.py", line 174, in start_learning
    self._reset_env(env_manager)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\trainer_controller.py", line 111, in _reset_env
    self._register_new_behaviors(env_manager, env_manager.first_step_infos)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\trainer_controller.py", line 268, in _register_new_behaviors
    self._create_trainers_and_managers(env_manager, new_behavior_ids)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\trainer_controller.py", line 165, in _create_trainers_and_managers
    self._create_trainer_and_manager(env_manager, behavior_id)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\trainer_controller.py", line 138, in _create_trainer_and_manager
    policy = trainer.create_policy(
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\ghost\trainer.py", line 330, in create_policy
    self.trainer.add_policy(parsed_behavior_id, internal_trainer_policy)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\sac\trainer.py", line 417, in add_policy
    self.model_saver.initialize_or_load()
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\model_saver\torch_model_saver.py", line 70, in initialize_or_load
    self._load_model(
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\model_saver\torch_model_saver.py", line 83, in _load_model
    saved_state_dict = torch.load(model_path)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\torch\serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'none\\checkpoint.pt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\capstone\.conda\envs\ml-agents-node\Scripts\mlagents-learn.exe\__main__.py", line 7, in <module>
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\learn.py", line 280, in main
    run_cli(parse_command_line())
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\learn.py", line 276, in run_cli
    run_training(run_seed, options)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\learn.py", line 158, in run_training
    write_training_status(run_logs_dir)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\learn.py", line 176, in write_training_status
    GlobalTrainingStatus.save_state(os.path.join(output_dir, TRAINING_STATUS_FILE_NAME))
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\training_status.py", line 101, in save_state
    with open(path, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'results\\node_001\\run_logs\\training_status.json'

(ml-agents-node) C:\Users\capstone\Documents\GitHub\Double_Agent\Assets\Config>mlagents-learn ./trainer_config.yaml --run-id node_001


                       
                        ___¦¦¦¦
                   +¦¦¦¦¦¦¦¦¦¦¦¦
              ,___m¯¯¯'  ,¦¦¦¯¦¦_                           ¦¦¦  ¦¦¦
            _¦¦¦¯'      _¦¦¯  ¦¦¦      __     __ ,__ ____   ,__ _¦¦¦_ ___    ,__
          _¦¦¦¯        _¦¦¯   ¦¦¦¦     ¦¦¦   ¦¦¦ ¦¦¦¦¯¯¯¦¦¦ ¦¦¦ ¯¦¦¦¯ ^¦¦¦  +¦¦¦
        _¦¦¦¦¦________¦¦¦      ¦¯      ¦¦¦   ¦¦¦ ¦¦¦    ¦¦¦ ¦¦¦  ¦¦¦   ¦¦¦_ ¦¦¦
        ¯¦¦¦¦¯¯¯¯¯¯¯¯¯¯¦¦_     ¦¦      ¦¦¦   ¦¦¦ ¦¦¦    ¦¦¦ ¦¦¦  ¦¦¦    ¦¦¦¦¦¦
          ^¦¦¦¦        ¯¦¦_   ¦¦¦¦     ¦¦¦¦_¦¦¦¦ ¦¦¦    ¦¦¦ ¦¦¦  ¦¦¦_    ¦¦¦¦`
            '¯¦¦¦_      ^¦¦¦  ¦¦¦       +¯¯¯¯ ¯¯ ^¯¯    `¯¯ `¯¯   '¯¯    ¦¦¦¦
               ¯¯¯¯¦___   ¦¦¦¦¦¦,                                      ¦¦¦¦¯
                   `¯¦¦¦¦¦¦¦¦¦¦¦
                        ¬`¯¯¯¦¦


 Version information:
  ml-agents: 0.23.0,
  ml-agents-envs: 0.23.0,
  Communicator API: 1.3.0,
  PyTorch: 1.7.1
2021-02-25 17:21:00 INFO [learn.py:275] run_seed set to 9453
2021-02-25 17:21:01 INFO [environment.py:204] Listening on port 5004. Start training by pressing the Play button in the Unity Editor.
2021-02-25 17:21:05 INFO [environment.py:110] Connected to Unity environment with package version 1.0.6 and communication version 1.0.0
2021-02-25 17:21:30 INFO [subprocess_env_manager.py:186] UnityEnvironment worker 0: environment stopping.
2021-02-25 17:21:30 INFO [trainer_controller.py:188] Learning was interrupted. Please wait while the graph is generated.
2021-02-25 17:21:30 INFO [trainer_controller.py:85] Saved Model
2021-02-25 17:21:30 WARNING [learn.py:170] Unable to save configuration to results\node_001\configuration.yaml. Make sure the directory exists
2021-02-25 17:21:30 WARNING [learn.py:185] Unable to save to results\node_001\run_logs\timers.json. Make sure the directory exists
Traceback (most recent call last):
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\capstone\.conda\envs\ml-agents-node\Scripts\mlagents-learn.exe\__main__.py", line 7, in <module>
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\learn.py", line 280, in main
    run_cli(parse_command_line())
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\learn.py", line 276, in run_cli
    run_training(run_seed, options)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\learn.py", line 158, in run_training
    write_training_status(run_logs_dir)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\learn.py", line 176, in write_training_status
    GlobalTrainingStatus.save_state(os.path.join(output_dir, TRAINING_STATUS_FILE_NAME))
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\training_status.py", line 101, in save_state
    with open(path, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'results\\node_001\\run_logs\\training_status.json'

(ml-agents-node) C:\Users\capstone\Documents\GitHub\Double_Agent\Assets\Config>mlagents-learn ./trainer_config.yaml --run-id node_001


                        
                        ___¦¦¦¦
                   +¦¦¦¦¦¦¦¦¦¦¦¦
              ,___m¯¯¯'  ,¦¦¦¯¦¦_                           ¦¦¦  ¦¦¦
            _¦¦¦¯'      _¦¦¯  ¦¦¦      __     __ ,__ ____   ,__ _¦¦¦_ ___    ,__
          _¦¦¦¯        _¦¦¯   ¦¦¦¦     ¦¦¦   ¦¦¦ ¦¦¦¦¯¯¯¦¦¦ ¦¦¦ ¯¦¦¦¯ ^¦¦¦  +¦¦¦
        _¦¦¦¦¦________¦¦¦      ¦¯      ¦¦¦   ¦¦¦ ¦¦¦    ¦¦¦ ¦¦¦  ¦¦¦   ¦¦¦_ ¦¦¦
        ¯¦¦¦¦¯¯¯¯¯¯¯¯¯¯¦¦_     ¦¦      ¦¦¦   ¦¦¦ ¦¦¦    ¦¦¦ ¦¦¦  ¦¦¦    ¦¦¦¦¦¦
          ^¦¦¦¦        ¯¦¦_   ¦¦¦¦     ¦¦¦¦_¦¦¦¦ ¦¦¦    ¦¦¦ ¦¦¦  ¦¦¦_    ¦¦¦¦`
            '¯¦¦¦_      ^¦¦¦  ¦¦¦       +¯¯¯¯ ¯¯ ^¯¯    `¯¯ `¯¯   '¯¯    ¦¦¦¦
               ¯¯¯¯¦___   ¦¦¦¦¦¦,                                      ¦¦¦¦¯
                   `¯¦¦¦¦¦¦¦¦¦¦¦
                        ¬`¯¯¯¦¦


 Version information:
  ml-agents: 0.23.0,
  ml-agents-envs: 0.23.0,
  Communicator API: 1.3.0,
  PyTorch: 1.7.1
2021-02-26 09:45:49 INFO [learn.py:275] run_seed set to 257
2021-02-26 09:45:49 INFO [environment.py:204] Listening on port 5004. Start training by pressing the Play button in the Unity Editor.
2021-02-26 09:45:54 INFO [environment.py:110] Connected to Unity environment with package version 1.0.6 and communication version 1.0.0
2021-02-26 09:46:54 INFO [subprocess_env_manager.py:186] UnityEnvironment worker 0: environment stopping.
2021-02-26 09:46:54 INFO [trainer_controller.py:85] Saved Model
Traceback (most recent call last):
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\capstone\.conda\envs\ml-agents-node\Scripts\mlagents-learn.exe\__main__.py", line 7, in <module>
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\learn.py", line 280, in main
    run_cli(parse_command_line())
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\learn.py", line 276, in run_cli
    run_training(run_seed, options)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\learn.py", line 153, in run_training
    tc.start_learning(env_manager)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\trainer_controller.py", line 174, in start_learning
    self._reset_env(env_manager)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\trainer_controller.py", line 109, in _reset_env
    env_manager.reset(config=new_config)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\env_manager.py", line 67, in reset
    self.first_step_infos = self._reset_env(config)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\subprocess_env_manager.py", line 299, in _reset_env
    ew.previous_step = EnvironmentStep(ew.recv().payload, ew.worker_id, {}, {})
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\subprocess_env_manager.py", line 95, in recv
    raise env_exception
mlagents_envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
         The environment does not need user interaction to launch
         The Agents' Behavior Parameters > Behavior Type is set to "Default"
         The environment and the Python interface have compatible versions.